version: "3.8"
services:
  db:
    image: mongo
    volumes:
      - ./volumes/mongodb/data:/data/db
    ports:
      - 27017:27017
    networks:
      - scout-net
  web:
    build:
      context: .
      dockerfile: containers/scout.dockerfile
    volumes:
      - ./scout:/scout/scout
      - ./scripts:/scout/scripts
      - ./tests:/scout/tests
    environment:
      FLASK_ENV: development
    ports:
      - 5000:5000
      - 443:443
    networks:
      - scout-net
    depends_on:
      - db
    command: [
    "./wait-for-it.sh", "db:27017", "--",
    "scout", "--host", "db", "--demo", "serve"]
networks:
  scout-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/24
